const moo = require("moo");



const patterns = {
	bars: ["SISYPHOS", "ZUM STARKEN AUGUST"],
	restaurants: [
		"McDonald's",
		"ROCOTO",
		"BABU RESTAURANT",
		"CHUTNIFY",
		"Burgermeister",
		"RISA CHICKEN",
		"CITYCHICKEN",
		"WALHALLA",
		"VIETBOWL",
		"Kai Maison",
		"Ristorante Roma",
		"DOCA CUISINE",
	],
	stores: ["GALERIA HERMANNPLATZ","Decathlon"],
	deliveryServices: ["Uber Eats", "UBER   *EATS", "Wolt"],
	supermarkets: ["BIO COMPANY", "EDEKA", "Lidl", "REWE", "Penny Market", "Penny", "PENNY DANKT","Galeria Markt"],
	travel: [
		"BVG",
		"Uber",
		"UBER",
		"Voi",
		"TIER",
		"BRITISH AIRWAYS",
		"DB Vertrieb",
		"FLIXBUS",
		"OEBB",
		"Wiener Linien",
	],
	cafes: ["DAS HOVEN", "The Barn", "Pavillon am Uf", "Kaffee 9"],
	pharmacy: ["APOTHEKE","DM Drogerie", "DM-Fil","easyApotheke"],
	health: ["OURARING", "Holmes Place"],
	culture: ["THE NEW YORK TIMES"],
	petSupplies: ["Zooplus", "DAS FUTTERHAUS"],
	diy: ["Bauhaus"],
	insurances: ["Allianz Versicherung"],
	charity: ["AKTION TIER"]
}




const stringToRegex = (element) => `\w*?${element}\w*?`;
const createLexerSet = (arrayOfPatterns) => {
	const keys = Object.keys(arrayOfPatterns)
	const lexerSet = keys.reduce((acc,setName) => {
		return {...acc, [setName]: new RegExp(arrayOfPatterns[setName].map(stringToRegex).join("|"))}
	},{})
	return lexerSet
}





const testStrings = [
	"OURARING	",
	"Voi	",
	"CHUTNIFY	",
	"DAS HOVEN              BERLIN        DE	",
	"The Barn	",
	"SumUp  *Pavillon am Uf Berlin        DE	",
	"Voi	",
	"Uber	",
	"Voi	",
	"SumUp  *Pavillon am Uf Berlin        DE	",
	"Kaffee 9 Berlin        Berlin        DE	",
	"EDEKA	",
	"Uber	",
	"BVG	",
	"BVG	",
	"APOTHEKE IM KARSTADT HERMANNPLATZ	",
	"THE NEW YORK TIMES     AMSTERDAM     NL	",
	"DM Drogerie Markt	",
	"Galeria Markth. B-     Berlin        DE	",
	"Kaffee 9 Berlin        Berlin        DE	",
	"EDEKA	",
	"Uber	",
	"Kaffee 9 Berlin        Berlin        DE	",
	"BVG	",
	"BVG	",
	"The Barn	",
	"	_BNSA* #3332           BERLIN        DE	",
	"BVG	",
	"Uber	",
	"BVG	",
	"Uber	",
	"DAS HOVEN              BERLIN        DE	",
	"	ADRIAN JOHN DOONAN	",
	"EDEKA	",
	"SumUp  *Pavillon am Uf Berlin        DE	",
	"	PayPal	",
	"EDEKA	",
	"SumUp  *Pavillon am Uf Berlin        DE	",
	"BVG	",
	"BVG	",
	"SUMUP  *LUCIANA NEMER  BERLIN        DE	",
	"	Zettle By PayPal	",
	"SISYPHOS EVENT GMBH	",
	"BVG	",
	"BVG	",
	"ROCOTO RESTAURANT	",
	"SumUp  *Pavillon am Uf Berlin        DE	",
	"	Kontosicherheit A	",
	"BVG	",
	"EDEKA	",
	"SumUp  *Pavillon am Uf Berlin        DE	",
	"BVG	",
	"EDEKA	",
	"ZUM STARKEN AUGUST     BERLIN        DE	",
	"BVG	",
	"BVG	",
	"McDonald's	",
	"	RUDIMARIE + MISSISMILL	",
	"SumUp  *Pavillon am Uf Berlin        DE	",
	"BVG	",
	"Zettle By PayPal	",
	"Kaffee 9 Berlin        Berlin        DE	",
	"OURARING	",
	"DM Drogerie Markt	",
	"Lidl	",
	"DM Drogerie Markt	",
	"	C Accardo Tom Hemps    Berlin        DE	",
	"BVG	",
	"BVG	",
	"BVG	",
	"McDonald's	",
	"Kaffee 9 Berlin        Berlin        DE	",
	"BVG	",
	"BABU RESTAURANT	",
	"Lidl	",
	"THE NEW YORK TIMES     AMSTERDAM     NL	",
	"Lidl	",
	"Burgermeister	",
	"EDEKA	",
	"Kai Maison             Berlin        DE	",
	"	ADRIAN JOHN DOONAN	",
	"DM Drogerie Markt	",
	"Galeria Markth. B-     Berlin        DE	",
	"EDEKA	",
	"EDEKA	",
	"EDEKA	",
	"RISA CHICKEN NEUKOELLN BERLIN        DE	",
	"	Kontosicherheit A	",
	"EDEKA	",
	"Zooplus	",
	"	PayPal	",
	"BVG	",
	"McDonald's	",
	"	C Accardo Tom Hemps    Berlin        DE	",
	"EDEKA	",
	"WWW.CITYCHICKENDASORIG BERLIN        DE	",
	"OURARING	",
	"BVG	",
	"EDEKA	",
	"EDEKA	",
	"Lidl	",
	"THE NEW YORK TIMES     AMSTERDAM     NL	",
	"EDEKA	",
	"Lidl	",
	"EDEKA	",
	"BVG	",
	"BVG	",
	"Burgermeister	",
	"Bauhaus	",
	"EDEKA	",
	"DAS FUTTERHAUS	",
	"	UDOMPHOL & LY GMBH	",
	"BVG	",
	"	SUMUP  *BURBACHER & GU BERLIN        DE	",
	"BVG	",
	"REWE	",
	"Uber	",
	"	COMEDY CAFÉ BERLIN	",
	"REWE	",
	"	ADRIAN JOHN DOONAN	",
	"DAS FUTTERHAUS	",
	"BIO COMPANY SE KST 128 Berlin        DE	",
	"Lidl	",
	"	Kontosicherheit A	",
	"	COMEDY CAFÉ BERLIN	",
	"Lidl	",
	"DM Drogerie Markt	",
	"Galeria Markth. B-     Berlin        DE	",
	"EDEKA	",
	"	COMEDY CAFÉ BERLIN	",
	"THE NEW YORK TIMES     NYTIMES.COM   NL	",
	"	COMEDY CAFÉ BERLIN	",
	"OURARING	",
	"EDEKA	",
	"REWE	",
	"Lidl	",
	"Uber Eats	",
	"	ADRIAN JOHN DOONAN	",
	"Uber	",
	"BVG	",
	"TIER* DE 12-1018647    BERLIN        DE	",
	"TIER* DE 12-1017646    BERLIN        DE	",
	"TIER* DE 12-1016661    BERLIN        DE	",
	"WALHALLA	",
	"TIER* DE 12-986081     BERLIN        DE	",
	"TIER* DE 12-943676     BERLIN        DE	",
	"TIER* DE 12-965592     BERLIN        DE	",
	"TIER* DE 12-966237     BERLIN        DE	",
	"	COMEDY CAFÉ BERLIN	",
	"DAS FUTTERHAUS	",
	"GALERIA HERMANNPLATZ   BERLIN        DE	",
	"WWW.CITYCHICKENDASORIG BERLIN        DE	",
	"TIER* DE 12-899623     BERLIN        DE	",
	"DM Drogerie Markt	",
	"TIER* DE 12-842578     BERLIN        DE	",
	"GALERIA HERMANNPLATZ   BERLIN        DE	",
	"	Wonnegau West	",
	"TIER* DE 12-803282     BERLIN        DE	",
	"BVG	",
	"	ADRIAN JOHN DOONAN	",
	"EDEKA 5514             POTSDAM       DE	",
	"	Kontosicherheit A	",
	"DAS FUTTERHAUS	",
	"GALERIA HERMANNPLATZ   BERLIN        DE	",
	"BVG	",
	"EDEKA	",
	"DM Drogerie Markt	",
	"	COMEDY CAFÉ BERLIN	",
	"Uber	",
	"TIER* DE 12-457998     BERLIN        DE	",
	"TIER* DE 12-441767     BERLIN        DE	",
	"TIER* DE 12-417399     BERLIN        DE	",
	"TIER* DE 12-416657     BERLIN        DE	",
	"BRITISH AIRWAYS	",
	"BRITISH AIRWAYS	",
	"Burgermeister	",
	"TIER* DE 12-314030     BERLIN        DE	",
	"TIER* DE 12-313699     BERLIN        DE	",
	"REWE	",
	"TIER* DE 12-257784     BERLIN        DE	",
	"TIER* DE 12-242912     BERLIN        DE	",
	"TIER* DE 12-207651     BERLIN        DE	",
	"OURARING	",
	"TIER* DE 12-125860     BERLIN        DE	",
	"TIER* DE 12-125633     BERLIN        DE	",
	"EDEKA	",
	"	SP MITEINANDERWACHSEN  BERLIN        DE	",
	"TIER* DE 12-45596      BERLIN        DE	",
	"Lidl	",
	"EDEKA	",
	"TIER MOBILITY SE       BERLIN        DE	",
	"EDEKA	",
	"REWE	",
	"TIER* DE 11-1871588    BERLIN        DE	",
	"EDEKA	",
	"BVG	",
	"	C Accardo Tom Hemps    Berlin        DE	",
	"Uber Eats	",
	"BVG	",
	"Uber	",
	"	GALA BLUMEN	",
	"GALERIA HERMANNPLATZ   BERLIN        DE	",
	"Wolt                   Germany       DE	",
	"Uber	",
	"BVG	",
	"Galeria Markth. B-     Berlin        DE	",
	"EDEKA	",
	"TIER* DE 11-1338512    BERLIN        DE	",
	"	ADRIAN JOHN DOONAN	",
	"UZR*easyApotheke Kottb Berlin        DE	",
	"EDEKA	",
	"EDEKA	",
	"Lidl	",
	"	Kontosicherheit A	",
	"	Belastung Jahresbeitrag	",
	"Galeria Markth. B-     Berlin        DE	",
	"	2079981214-2*          EVENTIM.DE    DE	",
	"Uber Eats	",
	"EDEKA	",
	"Lidl	",
	"Lidl	",
	"	AmRest	",
	"Decathlon	",
	"EDEKA	",
	"VIETBOWL	",
	"OURARING	",
	"EDEKA	",
	"EDEKA	",
	"REWE	",
	"	Yorck Kinogruppe	",
	"EDEKA	",
	"The Barn	",
	"SUMUP  *DOCA CUISINE   BERLIN        DE	",
	"EDEKA	",
	"EDEKA	",
	"TIER* DE 10-2333986    BERLIN        DE	",
	"TIER* DE 10-2333034    BERLIN        DE	",
	"TIER* DE 10-2318772    BERLIN        DE	",
	"TIER* DE S 6E831560    BERLIN        DE	",
	"	ADRIAN JOHN DOONAN	",
	"EDEKA	",
	"Uber	",
	"Penny Market	",
	"	JAVI GMBH	",
	"	HOTEL BOLZMANN	",
	"Uber	",
	"Uber	",
	"	bp	",
	"	bp	",
	"BVG	",
	"Wiener Linien 2281     Wien          AT	",
	"Wiener Linien 2368     Wien          AT	",
	"	Vitavien               Wien          AT	",
	"Ristorante Roma        Wien          AT	",
	"PENNY DANKT            WIEN          AT	",
	"DM-Fil. 0609           Wien          AT	",
	"OEBB Ticket Automat    Wien          AT	",
	"BVG JELBI-APP LOGPAY   BERLIN        DE	",
	"	SCOOM FOOD GERMANY GMB BERLIN        DE	",
	"UBER   *TRIP           HELP.UBER.COM NL	",
	"	HOTWIRE*SALES FINAL    1920-634-3150 FR	",
	"	CCB TRAINING SCHOOL    BERLIN        DE	",
	"Lidl Dienstleistung    Berlin        DE	",
	"EDEKA LAWRENZ          BERLIN        DE	",
	"WWW.CITYCHICKENDASORIG BERLIN        DE	",
	"PANNIER-APOTHEKE       Berlin        DE	",
	"Penny Am Hermannplatz  Berlin        DE	",
	"	Kontosicherheit A	",
	"EDEKA FIEBIG           BERLIN        DE	",
	"BAUHAUS 814            BERLIN        DE	",
	"UBER   *EATS           HELP.UBER.COM NL	",
	"	Yorck Kinogruppe       Berlin        DE	",
	"BVG APP/ONLINE LOGPAY  BERLIN        DE	",
	"	C Accardo Tom Hemps    Berlin        DE	",
	"EDEKA LAWRENZ          BERLIN        DE	",
	"FLIXBUS.COM            Berlin        DE	",
	"DB Vertrieb GmbH       430010881287  DE	",
	"DB Vertrieb GmbH       718375069611  DE	",
	"EDEKA FIEBIG           BERLIN        DE	",
	"REWE Markt GmbH-Zw     Berlin        DE	",
	"Burgermeister          Berlin        DE	",
];

const runThroughLexer = (string,patterns = {}) => {
	//console.log(`running ${string} through lexer`)
	const lexer = moo.compile({
		...patterns,
		unset: /.+?/,
	});
	const inferredType = lexer.reset(string.trim()).next()?.type
	//console.log('got type',inferredType)
	return inferredType !== "unset" ? inferredType : null
};
//console.log(JSON.stringify(testStrings.map(runThroughLexer), null, 4));

module.exports = {runThroughLexer, createLexerSet}